config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'posts#index'

  resources :posts do
    resources :tags
  end

  resources :tags do
    resources :posts
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_and_belongs_to_many :tags
  validates :title, :presence => true
end

app/models/tag.rb
class Tag <ActiveRecord::Base
  has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController <ApplicationController
  def index
    @posts = Post.all
    @tags = Tag.all
    render :index
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :author, :content, :tag)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def tag_params
     params.require(:tag).permit(:name)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClimbingBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="logo-area">
    <span class="logo">climbeginners</span>
  </div>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', posts_path() %></li>
        <li><%= link_to 'New Post', new_post_path() %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Log In', new_user_session_path() %></li>
        <li><%= link_to 'Sign Up', new_user_registration_path() %></li>
      </ul>
    </div>
  </div>
</nav>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<div class="form">
  <%= form_for @post do |f| %>
    <%= f.label :title %>
    <br>
    <%= f.text_field :title %>
    <br>
    <%= f.label :author %>
    <br>
    <%= f.text_field :author %>
    <br>
    <%= f.label :content %>
    <br>
    <%= f.text_field :content %>
    <br>
    <br>
    <%= f.submit 'Submit', class:'btn btn-primary' %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<span class="titles"><h1>Update Post</h1></span>
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="col-md-8">
  <div class="posts">
    <% @posts.each do |post| %>
    <%= link_to post.title, post_path(post) %> by <%= post.author %>
    <br>
    <br>
    <% end %>
  </div>
</div>

<div class="col-md-4">
  <div class="tag-section">
  <p>
    <h3>click a tag || see all its posts</h3>
    <p><%= link_to "Add a new Tag", new_tag_path() %>
    </p>
    <% @tags.each do |tag| %>
      <%= link_to tag.name, tag %><br>
    <% end %>
    <br>
  </div>
</div>

app/views/posts/new.html.erb
<span class="titles"><h1>Add a post</h1></span>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h3>Written by <%= @post.author %></h3>
<h3><%= @post.content %></h3>
<%= link_to 'Edit Post', edit_post_path(@post) %>
<p><%= link_to "Delete Post", post_path(@post), :method => 'delete' %></p>

app/views/tags/_form.html.erb
<%= form_for @tag do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
  <%= f.submit %>
  <% end %>

app/views/tags/edit.html.erb
<h1>Edit Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<ul>
  <% @tags.each do |tag| %>
    <li><%= tag.name %> || <%= link_to 'Show', tag %> || <%= link_to 'Edit', edit_tag_path(tag) %> </li>
    <% end %>
  </ul>
<br>

app/views/tags/new.html.erb
<h1>Add a new Tag</h1>
<%= render "form" %>

app/views/tags/show.html.erb
<% @tag each do |post| %>